server:
  port: 8761

security:
  basic:
    enabled: false

eureka:
  instance:
    hostname: localhost
  nonSecurePort: ${server.port}

client:
  registerWithEureka: false
  fetchRegistry: false
serviceUrl:
  defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server

